/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bid {
  'id' : string,
  'submittedAt' : bigint,
  'isWinner' : boolean,
  'bidderId' : string,
  'amount' : bigint,
}
export interface Stats {
  'totalBids' : bigint,
  'highestBid' : bigint,
  'averageBid' : bigint,
}
export interface UserProfile {
  'id' : string,
  'dob' : string,
  'gst' : string,
  'pan' : string,
  'name' : string,
  'createdAt' : bigint,
  'role' : string,
  'aadhaar' : string,
  'email' : string,
  'experience' : string,
  'contractAccepted' : boolean,
  'companyName' : string,
  'passwordHash' : string,
  'phone' : string,
  'outlets' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptContract' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'adminGetAllBidders' : ActorMethod<
    [string],
    { 'ok' : Array<UserProfile> } |
      { 'err' : string }
  >,
  'adminGetAllBids' : ActorMethod<
    [string],
    { 'ok' : Array<Bid> } |
      { 'err' : string }
  >,
  'adminLockBidding' : ActorMethod<
    [string, boolean],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'adminSelectWinner' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], UserProfile>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyBid' : ActorMethod<[string], { 'ok' : Bid } | { 'err' : string }>,
  'getMyProfile' : ActorMethod<
    [string],
    { 'ok' : UserProfile } |
      { 'err' : string }
  >,
  'getStats' : ActorMethod<[], Stats>,
  'getUserProfile' : ActorMethod<[Principal], UserProfile>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'login' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'placeBid' : ActorMethod<
    [string, bigint],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'register' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];